### PR TITLE
Dependency update

### PR DESCRIPTION
**Pull request by gilgardosh**

### CODE REVIEW

**Comment by Urigo** [comment]
@gilgardosh could you resolve conflicts?

**Comment by gilgardosh** [comment]
> @gilgardosh could you resolve conflicts?

Done

**Comment by Urigo** [comment]
@gilgardosh so you haven't removed the old images?

also did web pack 5 didn't work?

**Comment by gilgardosh** [comment]
@Urigo 
We need the image optimizers, next11 don't do it for us.
And the issues with webpack5 are related to the image optimizers..

IA similar issue discussed [here](https://github.com/cyrilwanner/next-optimized-images/issues/251), but no solution for now

**Comment by Urigo** [comment]
@gilgardosh I thought removing the image optimizers and using Next's Image component is having the same or maybe even better performance so why not remove and use Next's?

**Pull request merged**
