### PR TITLE
pub(graphql-codegen): "TypeScript with GraphQL done right" article

### PR DESCRIPTION
**Pull request by wittydeveloper**
Hi guys 👋🏼 

@dotansimha reached out to me on Twitter to publish [my last article](https://charlypoly.com/publications/typescript-with-graphql-done-right) "TypeScript with GraphQL done right" on your blog 🙂 

This PR add the given article to your blog:

Screenshot 2021-04-27 at 16 06 28
Screenshot 2021-04-27 at 16 06 37

I took the liberty to re-use the GraphQL Code Generator picture as cover image.

----
PS: @kamilkisiela, @dotansimha told me to sync with you in order to add a canonical URL to my original article link (https://charlypoly.com/publications/typescript-with-graphql-done-right) for SEO purposes (avoid content duplication)
Thanks!

### CODE REVIEW

**Comment by dotansimha** [comment]
Thank you @wittydeveloper !!  I deployed a preview, you can see it here: 

@Urigo do you want to take a quick look?

@kamilkisiela can you please help with the SEO thing and meta tags? Maybe we can just add a field under `meta` for that?

**Comment by Urigo** [comment]
wow awesome! welcome  @wittydeveloper and thank you so much for post!

I don't have a lot to say, @dotansimha I think you can approve it and merge when you want

just one question, for the CEO of SEO @kamilkisiela - should we do something about the other place this article is published in?
So Google won't punish us or the other place for duplicate content?

**Comment by dotansimha** [comment]
Thanks @wittydeveloper ! 
I added support for the `canonical` meta tag, and added that to your blog post.
Merging 🎉

**Comment by dotansimha** [comment]
@wittydeveloper deployed here: https://the-guild.dev/blog/graphql-with-typescript-done-right , thank you! 🎉 

I can see that it has `<link rel="canonical" href="https://charlypoly.com/publications/typescript-with-graphql-done-right">` - it seems correct, right?

**Comment by wittydeveloper** [comment]
@dotansimha It's perfect, thank you! 🏎️

**Pull request merged**
