### PR TITLE
feat: add branding page + logo download

### PR DESCRIPTION
**Pull request by notrab**
Adds a page to download The Guild logos.

### CODE REVIEW

**Comment by notrab** [comment]
I can't see errors from Vercel if someone can share those I can fix.

**Comment by ardatan** [comment]
```
[18:00:11.553] Cloning github.com/the-guild-org/the-guild-website (Branch: feat/brand-page, Commit: 6add0d0)
[18:00:13.666] Cloning completed: 2.113s
[18:00:13.667] Running "bash scripts/vercel-ignore-build-step.sh"
[18:00:13.675] VERCEL_GIT_COMMIT_AUTHOR_LOGIN: 
[18:00:13.675] ✅ - Build can proceed
[18:00:14.512] Installing build runtime...
[18:00:16.816] Build runtime installed: 2.304s
[18:00:17.636] Looking up build cache...
[18:00:26.978] Build cache downloaded [192.09 MB]: 8807.547ms
[18:00:27.344] Installing dependencies...
[18:00:27.663] yarn install v1.22.17
[18:00:27.779] [1/4] Resolving packages...
[18:00:28.552] success Already up-to-date.
[18:00:28.555] $ patch-package
[18:00:28.758] patch-package 6.4.7
[18:00:28.759] Applying patches...
[18:00:28.760] No patch files found
[18:00:28.769] $ husky install
[18:00:28.861] husky - Git hooks installed
[18:00:28.866] Done in 1.21s.
[18:00:28.881] Detected Next.js version: 12.1.6
[18:00:28.882] Running "yarn run build"
[18:00:29.241] yarn run v1.22.17
[18:00:29.282] $ yarn check-links && yarn generate:blogs-meta && next build && yarn generate:sitemap-and-rss
[18:00:29.682] $ yarn compile-ts check-links.ts dist/check-links.mjs && node dist/check-links.mjs
[18:00:30.076] $ ts-node -O '{"module":"commonjs"}' scripts/compile-ts check-links.ts dist/check-links.mjs
[18:00:33.264] ✅  Links checked!
[18:00:33.686] $ yarn compile-ts lib/generate-blogs-meta.ts dist/generate-blogs-meta.mjs && node dist/generate-blogs-meta.mjs
[18:00:34.115] $ ts-node -O '{"module":"commonjs"}' scripts/compile-ts lib/generate-blogs-meta.ts dist/generate-blogs-meta.mjs
[18:00:37.341] ✅  Blogs meta JSON generated
[18:00:38.579] warn  - You have enabled experimental feature(s).
[18:00:38.580] warn  - Experimental features are not covered by semver, and may cause unexpected or broken application behavior. Use them at your own risk.
[18:00:38.580] 
[18:00:38.646] info  - Checking validity of types...
[18:00:46.785] info  - Creating an optimized production build...
[18:00:57.312] Failed to compile.
[18:00:57.312] 
[18:00:57.312] ./public/static/logos.zip?lqip
[18:00:57.313] Module parse failed: Unexpected character '' (1:2)
[18:00:57.313] You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
[18:00:57.314] (Source code omitted for this binary file)
[18:00:57.314] 
[18:00:57.314] Import trace for requested module:
[18:00:57.314] ./public/ ?lqip sync ^\.\/.*$
[18:00:57.314] ./lib/images.ts
[18:00:57.314] ./ui/shared/Featured.tsx
[18:00:57.315] ./pages/open-source.tsx
[18:00:57.315] 
[18:00:57.315] ./public/static/logos.zip
[18:00:57.315] Module parse failed: Unexpected character '' (1:2)
[18:00:57.315] You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
[18:00:57.315] (Source code omitted for this binary file)
[18:00:57.315] 
[18:00:57.316] Import trace for requested module:
[18:00:57.316] ./public/ sync ^\.\/.*$
[18:00:57.316] ./lib/images.ts
[18:00:57.316] ./ui/shared/Featured.tsx
[18:00:57.316] ./pages/open-source.tsx
[18:00:57.316] 
[18:00:57.317] 
[18:00:57.317] > Build failed because of webpack errors
[18:00:57.370] error Command failed with exit code 1.
[18:00:57.371] info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[18:00:57.382] Error: Command "yarn run build" exited with 1
```

**Comment by dotansimha** [comment]
> I can't see errors from Vercel if someone can share those I can fix.

```


Import trace for requested module:
--
18:00:57.314 | ./public/ ?lqip sync ^\.\/.*$
18:00:57.314 | ./lib/images.ts
18:00:57.314 | ./ui/shared/Featured.tsx
18:00:57.315 | ./pages/open-source.tsx
18:00:57.315 |  
18:00:57.315 | ./public/static/logos.zip
18:00:57.315 | Module parse failed: Unexpected character '' (1:2)
18:00:57.315 | You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
18:00:57.315 | (Source code omitted for this binary file)
18:00:57.315 |  
18:00:57.316 | Import trace for requested module:
18:00:57.316 | ./public/ sync ^\.\/.*$
18:00:57.316 | ./lib/images.ts
18:00:57.316 | ./ui/shared/Featured.tsx
18:00:57.316 | ./pages/open-source.tsx
```

Something with the ZIP file that cannot be loaded by the bundler? I guess you can try to build locally and you should get the same error.

**Comment by dotansimha** [comment]
Great, thanks @notrab ! 
Can we maybe make the Download button look like a link? 
image

**Comment by notrab** [comment]
Hey @dotansimha I've updated the page to include a more prominent download button:

CleanShot 2022-06-16 at 10 03 28@2x

**Review by saihaj — CHANGES_REQUESTED** [review]
`title` isn't showing up here 
image

**Comment by notrab** [comment]
@saihaj fixed. Good spot!

**Review by dotansimha — APPROVED** [review]

**Pull request merged**
