### PR TITLE
sort blogs in pagination by date and if date is missing by title

### PR DESCRIPTION
**Pull request by B2o5T**

### CODE REVIEW

**Review by dotansimha — APPROVED** [review]
LGTM. @B2o5T do we want this fix to be in Nextra? and if so, should we wait for it?

**Comment by B2o5T** [comment]
No need to wait, let's use patch for the moment (since it's blocking only here).
It will be in nextra, there is already a similar proposal, so I'll push a PR in Nextra

https://github.com/shuding/nextra/issues/747#issue-1352823517
> 3. We also maintain blogs, however the articles are in ASC order by date, seems we have to use meta.json to change the order, can we respect the frontmatter.date and list in descending order

**Comment by B2o5T** [comment]
> @B2o5T in the preview I still see this:

I guess it's due previous cache, because locally it works 🥲

**Comment by dotansimha** [comment]
@B2o5T maybe CI doesn't apply the `pnpm` patches? 🤔 because you are right, it works fine locally, but then in CI it doesn't work well?

**Pull request closed without merging**
