### PR TITLE
replace `@mapbox/rehype-prism` with `shiki`, add copy to clipboard to code-blocks

### PR DESCRIPTION
**Pull request by B2o5T**
For better highlight and support svelte language

### CODE REVIEW

**Comment by B2o5T** [comment]
@jycouet

**Comment by jycouet** [comment]
@B2o5T what's needed to go from DRAFT? to ACTIVE to MERGED? 🥳

**Comment by B2o5T** [comment]
> @B2o5T what's needed to go from DRAFT? to ACTIVE to MERGED? 🥳
@jycouet soon!

**Review by dotansimha — APPROVED** [review]
LGTM. Rebase ?

**Pull request merged**
